clear; clc;

baseDir = fileparts(mfilename('fullpath'));
D = readtable(fullfile(baseDir, 'data', 'q1_interval.csv'));
SOC = readtable(fullfile(baseDir, 'data', 'q1_soc.csv'));

dt = 1/6;
n = height(D);

assert(n == 144, '购电数据应包含144个区间');
assert(height(SOC) == 145, '储能数据应包含145个时刻');
assert(all(abs(D.t_h(:) - (1:n)'*dt) < 1e-5), ...
    '购电数据时间应为区间末端');
assert(all(abs(SOC.t_h(:) - (0:n)'*dt) < 1e-5), ...
    '储能状态时间不匹配');

tMid = ((0:n-1)' + 0.5)*dt;
tEdge = (0:n)'*dt;

blue   = [0.000 0.447 0.698];
green  = [0.000 0.580 0.440];
orange = [0.835 0.369 0.000];
purple = [0.470 0.350 0.620];
ink    = [0.220 0.240 0.270];
gray   = [0.530 0.550 0.580];

fontCN = 'SimSun';
fontEN = 'Times New Roman';

fig = figure( ...
    'Units', 'centimeters', ...
    'Position', [3 3 15.5 14.0], ...
    'Color', 'w', ...
    'Renderer', 'painters');

tl = tiledlayout(fig, 3, 1, ...
    'Padding', 'compact', ...
    'TileSpacing', 'compact');

axA = nexttile(tl, 1);
hold(axA, 'on');

stairs(axA, tEdge, [D.g_kwh; D.g_kwh(end)], ...
    'Color', blue, 'LineWidth', 1.25);

ylim(axA, [0 max(1, 1.15*max(D.g_kwh))]);
ylabel(axA, '购电量 (kWh)', ...
    'FontName', fontCN, 'FontSize', 10);

title(axA, '(a) 最优计划购电量', ...
    'FontName', fontCN, 'FontSize', 10, ...
    'FontWeight', 'normal', 'Color', ink, ...
    'Units', 'normalized', ...
    'Position', [0 1.04 0], ...
    'HorizontalAlignment', 'left');

axB = nexttile(tl, 2);
hold(axB, 'on');

b1 = bar(axB, tMid, D.c_kwh, 0.94, ...
    'FaceColor', green, ...
    'EdgeColor', 'none');

b2 = bar(axB, tMid, -D.d_kwh, 0.94, ...
    'FaceColor', orange, ...
    'EdgeColor', 'none');

yline(axB, 0, '-', ...
    'Color', ink, 'LineWidth', 0.65, ...
    'HandleVisibility', 'off');

ylim(axB, [-1050 1050]);
yticks(axB, [-800 -400 0 400 800]);

ylabel(axB, '充放电量 (kWh)', ...
    'FontName', fontCN, 'FontSize', 10);

title(axB, '(b) 储能充放电安排', ...
    'FontName', fontCN, 'FontSize', 10, ...
    'FontWeight', 'normal', 'Color', ink, ...
    'Units', 'normalized', ...
    'Position', [0 1.04 0], ...
    'HorizontalAlignment', 'left');

lgd = legend(axB, [b1 b2], ...
    {'充电（正）', '放电（负）'}, ...
    'Location', 'northoutside', ...
    'Orientation', 'horizontal', ...
    'Box', 'off', ...
    'FontName', fontCN, 'FontSize', 9);
lgd.ItemTokenSize = [16 9];

axC = nexttile(tl, 3);
hold(axC, 'on');

yline(axC, 10800, '--', ...
    'Color', gray, 'LineWidth', 0.75, ...
    'HandleVisibility', 'off');

yline(axC, 1200, '--', ...
    'Color', gray, 'LineWidth', 0.75, ...
    'HandleVisibility', 'off');

yline(axC, 6000, ':', ...
    'Color', [0.65 0.66 0.68], ...
    'LineWidth', 0.75, ...
    'HandleVisibility', 'off');

plot(axC, SOC.t_h, SOC.E_kwh, ...
    '-', 'Color', purple, 'LineWidth', 1.45);

plot(axC, SOC.t_h([1 end]), SOC.E_kwh([1 end]), ...
    'o', 'LineStyle', 'none', ...
    'MarkerSize', 4.5, ...
    'MarkerEdgeColor', purple, ...
    'MarkerFaceColor', 'w', ...
    'LineWidth', 1.1, ...
    'Clipping', 'off');

ylim(axC, [0 12000]);
yticks(axC, [1200 6000 10800]);

ylabel(axC, '储能电量 (kWh)', ...
    'FontName', fontCN, 'FontSize', 10);

xlabel(axC, '时刻', ...
    'FontName', fontCN, 'FontSize', 10);

title(axC, '(c) 储能电量与运行边界', ...
    'FontName', fontCN, 'FontSize', 10, ...
    'FontWeight', 'normal', 'Color', ink, ...
    'Units', 'normalized', ...
    'Position', [0 1.04 0], ...
    'HorizontalAlignment', 'left');

tickHours = 0:4:24;
tickLabels = arrayfun(@(h) sprintf('%02d:00', h), ...
    tickHours, 'UniformOutput', false);

for ax = [axA axB axC]
    set(ax, ...
        'FontName', fontEN, ...
        'FontSize', 9, ...
        'LineWidth', 0.7, ...
        'XColor', ink, ...
        'YColor', ink, ...
        'Color', 'w', ...
        'Box', 'off', ...
        'TickDir', 'out', ...
        'TickLength', [0.008 0.008], ...
        'XMinorTick', 'off', ...
        'YMinorTick', 'off', ...
        'XGrid', 'off', ...
        'YGrid', 'on', ...
        'GridColor', [0.65 0.67 0.70], ...
        'GridAlpha', 0.16, ...
        'GridLineStyle', '-', ...
        'Layer', 'top');

    xlim(ax, [0 24]);
    xticks(ax, tickHours);
    xticklabels(ax, tickLabels);

    ax.YAxis.Exponent = 0;
    ax.YLabel.FontName = fontCN;
    ax.YLabel.FontSize = 10;
    ax.Title.FontName = fontCN;
    ax.Title.FontSize = 10;
end

axC.YGrid = 'off';
axC.XLabel.FontName = fontCN;
axC.XLabel.FontSize = 10;

xticklabels(axA, {});
xticklabels(axB, {});
linkaxes([axA axB axC], 'x');

outDir = fullfile(baseDir, 'figures_refined');
if ~exist(outDir, 'dir')
    mkdir(outDir);
end

drawnow;

exportgraphics(fig, fullfile(outDir, 'fig2_optimal_strategy.pdf'), ...
    'ContentType', 'vector', ...
    'BackgroundColor', 'white');

exportgraphics(fig, fullfile(outDir, 'fig2_optimal_strategy.png'), ...
    'Resolution', 600, ...
    'BackgroundColor', 'white');