clear; clc;

baseDir = fileparts(mfilename('fullpath'));
S = readtable(fullfile(baseDir, 'data', 'q1_sensitivity.csv'));

cap = S(isfinite(S.window_kwh) & isfinite(S.cost_cap), :);
pow = S(isfinite(S.p_kw) & isfinite(S.cost_pow), :);

cap = sortrows(cap, 'window_kwh');
pow = sortrows(pow, 'p_kw');

idxCap = find(abs(cap.window_kwh - 9600) < 1e-5);
idxPow = find(abs(pow.p_kw - 5000) < 1e-5);

assert(numel(idxCap) == 1, '容量数据应包含唯一的9600 kWh基准点');
assert(numel(idxPow) == 1, '功率数据应包含唯一的5000 kW基准点');
assert(abs(cap.cost_cap(idxCap) - pow.cost_pow(idxPow)) < 1e-3, ...
    '两组敏感性分析的基准费用不一致');

xCap = cap.window_kwh / 1000;
yCap = cap.cost_cap / 10000;
xPow = pow.p_kw / 1000;
yPow = pow.cost_pow / 10000;

blue  = [0.000 0.447 0.698];
green = [0.000 0.580 0.440];
red   = [0.835 0.369 0.000];
ink   = [0.220 0.240 0.270];

fontCN = 'SimSun';
fontEN = 'Times New Roman';

fig = figure( ...
    'Units', 'centimeters', ...
    'Position', [3 3 16.5 7.3], ...
    'Color', 'w', ...
    'Renderer', 'painters');

tl = tiledlayout(fig, 1, 2, ...
    'Padding', 'compact', ...
    'TileSpacing', 'compact');

axL = nexttile(tl, 1);
hold(axL, 'on');

plot(axL, xCap, yCap, '-o', ...
    'Color', blue, ...
    'LineWidth', 1.25, ...
    'MarkerSize', 4.5, ...
    'MarkerFaceColor', 'w', ...
    'MarkerEdgeColor', blue);

xline(axL, xCap(idxCap), ':', ...
    'Color', [0.72 0.73 0.75], ...
    'LineWidth', 0.8, ...
    'HandleVisibility', 'off');

plot(axL, xCap(idxCap), yCap(idxCap), 's', ...
    'MarkerSize', 6.5, ...
    'MarkerFaceColor', red, ...
    'MarkerEdgeColor', 'w', ...
    'LineWidth', 0.8);

xlabel(axL, '可用容量窗口 (MWh)', ...
    'FontName', fontCN, 'FontSize', 10);

ylabel(axL, '全天购电费 (万元)', ...
    'FontName', fontCN, 'FontSize', 10);

title(axL, '(a) 容量窗口敏感性', ...
    'FontName', fontCN, 'FontSize', 10, ...
    'FontWeight', 'normal', 'Color', ink, ...
    'Units', 'normalized', ...
    'Position', [0 1.04 0], ...
    'HorizontalAlignment', 'left');

axR = nexttile(tl, 2);
hold(axR, 'on');

plot(axR, xPow, yPow, '-^', ...
    'Color', green, ...
    'LineWidth', 1.25, ...
    'MarkerSize', 4.5, ...
    'MarkerFaceColor', 'w', ...
    'MarkerEdgeColor', green);

xline(axR, xPow(idxPow), ':', ...
    'Color', [0.72 0.73 0.75], ...
    'LineWidth', 0.8, ...
    'HandleVisibility', 'off');

plot(axR, xPow(idxPow), yPow(idxPow), 's', ...
    'MarkerSize', 6.5, ...
    'MarkerFaceColor', red, ...
    'MarkerEdgeColor', 'w', ...
    'LineWidth', 0.8);

xlabel(axR, '充放电功率上限 (MW)', ...
    'FontName', fontCN, 'FontSize', 10);

title(axR, '(b) 功率上限敏感性', ...
    'FontName', fontCN, 'FontSize', 10, ...
    'FontWeight', 'normal', 'Color', ink, ...
    'Units', 'normalized', ...
    'Position', [0 1.04 0], ...
    'HorizontalAlignment', 'left');

allCost = [yCap; yPow];
yMin = floor((min(allCost) - 0.10)*5)/5;
yMax = ceil((max(allCost) + 0.10)*5)/5;
yTicks = yMin:0.2:yMax;
ySpan = yMax - yMin;

for ax = [axL axR]
    set(ax, ...
        'FontName', fontEN, ...
        'FontSize', 9, ...
        'LineWidth', 0.7, ...
        'XColor', ink, ...
        'YColor', ink, ...
        'Color', 'w', ...
        'Box', 'off', ...
        'TickDir', 'out', ...
        'TickLength', [0.012 0.012], ...
        'XMinorTick', 'off', ...
        'YMinorTick', 'off', ...
        'XGrid', 'off', ...
        'YGrid', 'on', ...
        'GridColor', [0.65 0.67 0.70], ...
        'GridAlpha', 0.18, ...
        'GridLineStyle', '-', ...
        'Layer', 'top');

    ylim(ax, [yMin yMax]);
    yticks(ax, yTicks);
    ytickformat(ax, '%.1f');

    ax.YAxis.Exponent = 0;
    ax.XLabel.FontName = fontCN;
    ax.XLabel.FontSize = 10;
    ax.Title.FontName = fontCN;
    ax.Title.FontSize = 10;
end

axL.YLabel.FontName = fontCN;
axL.YLabel.FontSize = 10;

xlim(axL, [min(xCap)-0.45, max(xCap)+0.45]);
xticks(axL, xCap);
xtickformat(axL, '%.1f');

xlim(axR, [0, max(xPow)+0.5]);
xticks(axR, [0 2.5 5 7.5 10]);
xtickformat(axR, '%g');

text(axL, xCap(idxCap)-0.18, yCap(idxCap)+0.075*ySpan, ...
    {'当前配置', '9.6 MWh'}, ...
    'FontName', fontCN, ...
    'FontSize', 8.5, ...
    'Color', red, ...
    'HorizontalAlignment', 'right', ...
    'VerticalAlignment', 'bottom', ...
    'Interpreter', 'none');

text(axR, xPow(idxPow)+0.25, yPow(idxPow)+0.075*ySpan, ...
    {'当前配置', '5.0 MW'}, ...
    'FontName', fontCN, ...
    'FontSize', 8.5, ...
    'Color', red, ...
    'HorizontalAlignment', 'left', ...
    'VerticalAlignment', 'bottom', ...
    'Interpreter', 'none');

linkaxes([axL axR], 'y');

outDir = fullfile(baseDir, 'figures_refined');
if ~exist(outDir, 'dir')
    mkdir(outDir);
end

drawnow;

exportgraphics(fig, fullfile(outDir, 'fig3_sensitivity.pdf'), ...
    'ContentType', 'vector', ...
    'BackgroundColor', 'white');

exportgraphics(fig, fullfile(outDir, 'fig3_sensitivity.png'), ...
    'Resolution', 600, ...
    'BackgroundColor', 'white');